[aliases]
g = 'git'
ga = 'git add'
gaa = 'git add --all'
gap = 'git apply'
gapa = 'git add --patch'
gau = 'git add --update'
gb = 'git branch'
gba = 'git branch --all'
gbd = 'git branch --delete'
gbD = 'git branch --delete --force'
gbr = 'git branch --remote'
gcb = 'git checkout -b'
gcl = 'git clone --recurse-submodules'
gco = 'git checkout'
gc = 'git commit --verbose'
gca = 'git commit --verbose --all'
gcam = 'git commit --all --message'
gcmsg = 'git commit --message'
gd = 'git diff'
gdca = 'git diff --cached'
gds = 'git diff --staged'
gf = 'git fetch'
gfo = 'git fetch origin'
gl = 'git pull'
glo = 'git log --oneline --decorate'
glog = 'git log --oneline --decorate --graph'
gp = 'git push'
gpd = 'git push --dry-run'
gpf = 'git push --force-with-lease'
grb = 'git rebase'
grba = 'git rebase --abort'
grbc = 'git rebase --continue'
grbi = 'git rebase --interactive'
grh = 'git reset'
grhh = 'git reset --hard'
grs = 'git restore'
grst = 'git restore --staged'
gst = 'git status'
gss = 'git status --short'
gsb = 'git status --short --branch'
gsta = 'git stash push'
gstaa = 'git stash apply'
gstd = 'git stash drop'
gstl = 'git stash list'
gstp = 'git stash pop'
gsts = 'git stash show --patch'
gsw = 'git switch'
gswc = 'git switch --create'
