[aliases]
k = 'kubectl'
kaf = 'kubectl apply -f'
kapk = 'kubectl apply -k'
keti = 'kubectl exec -t -i'
kcuc = 'kubectl config use-context'
kcsc = 'kubectl config set-context'
kcdc = 'kubectl config delete-context'
kccc = 'kubectl config current-context'
kcgc = 'kubectl config get-contexts'
kdel = 'kubectl delete'
kdelf = 'kubectl delete -f'
kdelk = 'kubectl delete -k'
kge = 'kubectl get events --sort-by=".lastTimestamp"'
kgew = 'kubectl get events --sort-by=".lastTimestamp" --watch'
kgp = 'kubectl get pods'
kgpl = 'kubectl get pods -l'
kgpn = 'kubectl get pods -n'
kgpsl = 'kubectl get pods --show-labels'
kgpa = 'kubectl get pods --all-namespaces'
kgpw = 'kubectl get pods --watch'
kgpwide = 'kubectl get pods -o wide'
kep = 'kubectl edit pods'
kdp = 'kubectl describe pods'
kdelp = 'kubectl delete pods'
kgpall = 'kubectl get pods --all-namespaces -o wide'
kgs = 'kubectl get svc'
kgsa = 'kubectl get svc --all-namespaces'
kgsw = 'kubectl get svc --watch'
kgswide = 'kubectl get svc -o wide'
kes = 'kubectl edit svc'
kds = 'kubectl describe svc'
kdels = 'kubectl delete svc'
kgi = 'kubectl get ingress'
kgia = 'kubectl get ingress --all-namespaces'
kei = 'kubectl edit ingress'
kdi = 'kubectl describe ingress'
kdeli = 'kubectl delete ingress'
kgns = 'kubectl get namespaces'
kens = 'kubectl edit namespace'
kdns = 'kubectl describe namespace'
kdelns = 'kubectl delete namespace'
kcn = 'kubectl config set-context --current --namespace'
kgcm = 'kubectl get configmaps'
kgcma = 'kubectl get configmaps --all-namespaces'
kecm = 'kubectl edit configmap'
kdcm = 'kubectl describe configmap'
kdelcm = 'kubectl delete configmap'
kgsec = 'kubectl get secret'
kgseca = 'kubectl get secret --all-namespaces'
kdsec = 'kubectl describe secret'
kdelsec = 'kubectl delete secret'
kgd = 'kubectl get deployment'
kgda = 'kubectl get deployment --all-namespaces'
kgdw = 'kubectl get deployment --watch'
kgdwide = 'kubectl get deployment -o wide'
ked = 'kubectl edit deployment'
kdd = 'kubectl describe deployment'
kdeld = 'kubectl delete deployment'
ksd = 'kubectl scale deployment'
krsd = 'kubectl rollout status deployment'
krrd = 'kubectl rollout restart deployment'
kgrs = 'kubectl get replicaset'
kdrs = 'kubectl describe replicaset'
kers = 'kubectl edit replicaset'
krh = 'kubectl rollout history'
kru = 'kubectl rollout undo'
kgss = 'kubectl get statefulset'
kgssa = 'kubectl get statefulset --all-namespaces'
kgssw = 'kubectl get statefulset --watch'
kgsswide = 'kubectl get statefulset -o wide'
kess = 'kubectl edit statefulset'
kdss = 'kubectl describe statefulset'
kdelss = 'kubectl delete statefulset'
ksss = 'kubectl scale statefulset'
krsss = 'kubectl rollout status statefulset'
krrss = 'kubectl rollout restart statefulset'
kpf = 'kubectl port-forward'
kga = 'kubectl get all'
kgaa = 'kubectl get all --all-namespaces'
kl = 'kubectl logs'
kl1h = 'kubectl logs --since 1h'
kl1m = 'kubectl logs --since 1m'
kl1s = 'kubectl logs --since 1s'
klf = 'kubectl logs -f'
klf1h = 'kubectl logs --since 1h -f'
klf1m = 'kubectl logs --since 1m -f'
klf1s = 'kubectl logs --since 1s -f'
kcp = 'kubectl cp'
kgno = 'kubectl get nodes'
kgnosl = 'kubectl get nodes --show-labels'
keno = 'kubectl edit node'
kdno = 'kubectl describe node'
kdelno = 'kubectl delete node'
kgpvc = 'kubectl get pvc'
kgpvca = 'kubectl get pvc --all-namespaces'
kgpvcw = 'kubectl get pvc --watch'
kepvc = 'kubectl edit pvc'
kdpvc = 'kubectl describe pvc'
kdelpvc = 'kubectl delete pvc'
kdsa = 'kubectl describe sa'
kdelsa = 'kubectl delete sa'
kgds = 'kubectl get daemonset'
kgdsa = 'kubectl get daemonset --all-namespaces'
kgdsw = 'kubectl get daemonset --watch'
keds = 'kubectl edit daemonset'
kdds = 'kubectl describe daemonset'
kdelds = 'kubectl delete daemonset'
kgcj = 'kubectl get cronjob'
kecj = 'kubectl edit cronjob'
kdcj = 'kubectl describe cronjob'
kdelcj = 'kubectl delete cronjob'
kgj = 'kubectl get job'
kej = 'kubectl edit job'
kdj = 'kubectl describe job'
kdelj = 'kubectl delete job'
