[aliases]
npmg = 'npm i -g'
npmS = 'npm i -S'
npmD = 'npm i -D'
npmF = 'npm i -f'
npmO = 'npm outdated'
npmU = 'npm update'
npmV = 'npm -v'
npmL = 'npm list'
npmL0 = 'npm ls --depth=0'
npmst = 'npm start'
npmt = 'npm test'
npmR = 'npm run'
npmP = 'npm publish'
npmI = 'npm init'
npmi = 'npm info'
npmSe = 'npm search'
npmrd = 'npm run dev'
npmrb = 'npm run build'
