(module
  (import "winuxsh:plugin/host" "stdout_write" (func $stdout_write (param i32 i32) (result i32)))
  (import "winuxsh:plugin/host" "arg_count" (func $arg_count (result i32)))
  (import "winuxsh:plugin/host" "arg_len" (func $arg_len (param i32) (result i32)))
  (import "winuxsh:plugin/host" "arg_read" (func $arg_read (param i32 i32) (result i32)))
  (import "winuxsh:plugin/host" "cwd_len" (func $cwd_len (result i32)))
  (import "winuxsh:plugin/host" "cwd_read" (func $cwd_read (param i32) (result i32)))
  (memory (export "memory") 1)
  (data (i32.const 0) "hello from wasm\n")
  (data (i32.const 32) "cwd:")
  (data (i32.const 48) "\n")
  (data (i32.const 160) "arg0:")
  (func (export "winuxsh_plugin_main") (result i32)
    (local $cwd_len i32)
    (local $argc i32)
    (local $arg_len i32)
    (drop (call $stdout_write (i32.const 0) (i32.const 16)))
    (local.set $cwd_len (call $cwd_len))
    (if (i32.lt_s (local.get $cwd_len) (i32.const 0))
      (then (return (i32.const 41)))
    )
    (if (i32.ne (call $cwd_read (i32.const 64)) (local.get $cwd_len))
      (then (return (i32.const 42)))
    )
    (drop (call $stdout_write (i32.const 32) (i32.const 4)))
    (drop (call $stdout_write (i32.const 64) (local.get $cwd_len)))
    (drop (call $stdout_write (i32.const 48) (i32.const 1)))
    (local.set $argc (call $arg_count))
    (if (i32.lt_s (local.get $argc) (i32.const 0))
      (then (return (i32.const 43)))
    )
    (if (i32.gt_s (local.get $argc) (i32.const 0))
      (then
        (local.set $arg_len (call $arg_len (i32.const 0)))
        (if (i32.lt_s (local.get $arg_len) (i32.const 0))
          (then (return (i32.const 44)))
        )
        (if (i32.ne (call $arg_read (i32.const 0) (i32.const 256)) (local.get $arg_len))
          (then (return (i32.const 45)))
        )
        (drop (call $stdout_write (i32.const 160) (i32.const 5)))
        (drop (call $stdout_write (i32.const 256) (local.get $arg_len)))
        (drop (call $stdout_write (i32.const 48) (i32.const 1)))
      )
    )
    (i32.const 0)
  )
)
